[package]
name = "ch-udf-common"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1"
arrow = "57"
serde = "1"
serde_json = "1"
url = "2"
thiserror = "2.0"
tower = { version = "0.5", features = ["retry", "limit", "util"] }
alloy =  "1" 
alloy-json-rpc = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
futures-core = "0.3"
duration-str = "0.17"
serde_qs = "0.15"
itertools = "0.14"
serde-inline-default = "0.2"
backoff = "0.4"
futures = "0.3"
object_store = { version = "0.12", features = ["http", "aws"] }
querystring = "1"
